[tool.poetry]
name = "streetscope"
version = "0.1.0"
description = "This package handles downloading, cleaning, analyzing street view imagery"
authors = ["koito19960406"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
